---
    - name: update packages
      hosts: ubuntu
      become: true
    
      tasks:
        - name: APT package updater
          ansible.builtin.apt:
                upgrade: yes
                update_cache: yes